### ISSUE TITLE
I want some news

### ISSUE THREAD

**Issue by josechagas** [thomazfeitoza/gn-api-sdk-ios#2]
Hey, I am thinking to use this api, but I can see that it's working, so What I want to know is if you pretend to continue developing it or not?

**Comment by chuckbnorris** [comment]
@josechagas 

Hi! My name is Tiago and I am from the Technical Consulting Team on Integrations of Gerencianet.

This repository contains a simple lib to facilitate the integration of your application with the Gerencianet services. Rest assured, the idea is to continue developing this repository, but there is no exact timeframe for doing so.

Check out the means of communication with our company: https://dev.gerencianet.com.br/docs/fale-conosco

Any questions or additional information, we are at your disposal.
